name: Split String Workflow

on:
  push:
    branches: [ main ]

env:
  SECOND_PART: ""

jobs:
  split_string_job:
    runs-on: ubuntu-latest
    steps:
      - name: Split string and store second part
        run: |
          str="sushant/kumar"
          arr=(${str//\// })
          echo "Second part: ${arr[1]}"
          echo "::set-env name=SECOND_PART::${arr[1]}"
        env:
          SECOND_PART: ${{ env.SECOND_PART }}
