name: Split String Workflow

on:
  push:
    branches: [ main ]

env:
  SECOND_PART: ""

jobs:
  split_string_job:
    runs-on: ubuntu-latest
    steps:
      - name: Split string and store second part
        run: |
          str="sushant/kumar"
          arr=(${str//\// })
          echo "Second part: ${arr[1]}"
          echo "SECOND_PART=${arr[1]}" >> $GITHUB_ENV
          echo ${{github.event.repository.owner.name}}
          echo ${{github.repository.default_branch}}
        env:
          SECOND_PART: ${{ env.SECOND_PART }}
